[package]
name = "quit_macros"
version = "1.1.3"
authors = ["dylni"]
edition = "2018"
exclude = [".*", "/rustfmt.toml", "/tests"]
description = """
Procedural macros used by crate quit
"""
repository = "https://github.com/dylni/quit"
readme = "description.md"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true
