name: build

on:
  pull_request:
  push:
    branches:
    - master
  schedule:
  - cron: 0 0 * * FRI

jobs:
  build:
    runs-on: ${{ matrix.platform }}
    env:
      RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - run: cargo install cargo-hack
    - run: cargo hack clippy --feature-powerset --optional-deps
    - run: cargo hack clippy --feature-powerset --optional-deps --tests
    - run: cargo fmt -- --check
    timeout-minutes: 5
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
  test:
    needs: [build]
    runs-on: ${{ matrix.platform }}
    env:
      RUSTFLAGS: -Dwarnings
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 10
    - run: rustup install ${{ matrix.version }}
    - run: rustup default ${{ matrix.version }}
    - run: cargo test --no-default-features
    - run: cargo test --all-features
    - run: cargo test --all-features --release
    timeout-minutes: 10
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
        version: [1.48.0, stable, beta, nightly]
